services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # Porta da fila
      - "15672:15672"     # Painel de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    mem_limit: 256m
    cpus: 0.5
    healthcheck:
      test: ['CMD', 'rabbitmqctl', 'status']
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - api

  translation-api:
    build: ./translation-api
    container_name: translation-api
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./translation-api:/app
      - /app/node_modules
    networks:
      - api

  translation-worker:
    build: ./translation-worker
    container_name: translation-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./translation-worker:/app
      - /app/node_modules
    env_file:
      - ./translation-worker/.env
    networks:
      - api    

networks:
  api:
    driver: bridge